---

- name: Import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: Import tooling tasks
  ansible.builtin.import_tasks: setup-tooling.yml

- name: Import configs tasks
  ansible.builtin.import_tasks: create-configs.yml

- name: Import installation tasks
  ansible.builtin.import_tasks: run-install.yml
