---

use_rhsm_repos: true

cockpit_enabled: true
cockpit_started: true
cockpit_manage_firewall: true

_cockpit_packages:
  - cockpit
  - cockpit-networkmanager
  - cockpit-packagekit
  - cockpit-selinux
  - cockpit-storaged
  - cockpit-machines

cockpit_config:
  WebService:
    LoginTitle: "{{ ec2_name_prefix }} Device Edge Workshop"
    MaxStartups: "{{ student_total }}"
  Session:
    IdleTimeout: 60
    Banner: "{{ ec2_name_prefix }} Device Edge Workshop"

_extra_hypervisor_packages:
  - genisoimage
  - isomd5sum

_kvm_packages:
  - qemu-kvm
  - libvirt
  - virt-install
  - virt-viewer

virtual_machines_yaml: |-
  {% for student_number in range(1, student_total + 1) %}
  - name: student{{ student_number }}-edge-device
    ip: '192.168.122.{{ 10 + student_number }}'
    num: {{ student_number }}
  {% endfor %}
