---

- name: create student users in gitea
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:3001/api/v1/admin/users"
    validate_certs: false
    user: lab-instructor
    password: '{{ admin_password }}'
    force_basic_auth: true
    body_format: json
    method: POST
    body:
      username: "student{{ student_number }}"
      password: "{{ admin_password }}"
      email: "student{{ student_number }}@email.me"
      must_change_password: false
    status_code:
      - 201
      - 422
  loop: "{{ range(1, (student_total + 1), 1)|list }}"
  loop_control:
    loop_var: student_number
  when:
    - workshop_or_demo == 'workshop' or
      demo_type == 'summit_connect_2023'

- name: Create single user for demos
  ansible.builtin.uri:
    url: "http://{{ ansible_host }}:3001/api/v1/admin/users"
    validate_certs: false
    user: lab-instructor
    password: '{{ admin_password }}'
    force_basic_auth: true
    body_format: json
    method: POST
    body:
      username: "{{ gitea_demo_user }}"
      password: "{{ admin_password }}"
      email: "{{ gitea_demo_user }}@email.me"
      must_change_password: false
    status_code:
      - 201
      - 422
  when:
    - workshop_or_demo == 'demo'
    - demo_type != 'summit_connect_2023'
