---

- name: import pre-flight tasks
  ansible.builtin.import_tasks: pre-flight.yml

- name: include install tasks
  when:
    - install_gitea | bool
  block:

    - name: include firewall tasks
      ansible.builtin.include_tasks:
        file: open-firewall-ports.yml

    - name: include copy build info tasks
      ansible.builtin.include_tasks:
        file: copy-build-info.yml
      loop_control:
        loop_var: container
      loop: "{{ podman_kube_specs[0].kube_file_content.spec.containers }}"

    - name: include tasks to template out app.ini
      ansible.builtin.include_tasks:
        file: push-gitea-config.yml

    - name: include tasks to build container
      ansible.builtin.include_tasks:
        file: build-container.yml
      loop_control:
        loop_var: container
      loop: "{{ podman_kube_specs[0].kube_file_content.spec.containers }}"

    - name: include kube spec template tasks
      ansible.builtin.include_tasks:
        file: push-kube-play.yml
      loop_control:
        loop_var: kube_spec
      loop: "{{ podman_kube_specs }}"

    - name: include podman kube play tasks
      ansible.builtin.include_tasks:
        file: podman-kube-play.yml
      loop_control:
        loop_var: kube_spec
      loop: "{{ podman_kube_specs }}"

- name: tasks to configure gitea
  when:
    - configure_gitea | bool
  block:
    - name: include config/users/repos tasks
      ansible.builtin.include_tasks:
        file: "{{ tasks_file }}"
      loop:
        - initial-gitea-config.yml
        - create-gitea-users.yml
        - create-gitea-repos.yml
        - create-gitea-webhooks.yml
      loop_control:
        loop_var: tasks_file

    - name: include tasks to populate repos
      ansible.builtin.include_tasks:
        file: populate-repos.yml
      loop: "{{ range(1, (student_total + 1), 1)|list }}"
      loop_control:
        loop_var: student_number
