---

- name: dump the lock file
  ansible.builtin.file:
    path: "/var/www/html/{{ builder_blueprint_name }}/repo/.lock"
    state: absent
  become: true

- name: copy repo dir to {{ build_dir }}/ostree-repo
  ansible.builtin.copy:
    src: "/var/www/html/{{ builder_blueprint_name }}/repo"
    dest: "{{ build_dir }}/ostree-repo/"
    remote_src: true


- name: Create ostree-repo students directory if it does not exist
  ansible.builtin.file:
    path:  /var/www/html/student-repos
    state: directory
  become: true

- name: Allow containers to access and modify files in /var/www/html/student-repos
  community.general.sefcontext:
    target: '/var/www/html/student-repos(/.*)?'
    setype: container_file_t
    state: present
  become: true

- name: Apply new SELinux file context to filesystem
  ansible.builtin.command: restorecon -R /var/www/html/student-repos
  become: true
