---

- name: Configure DNS record for {{ route53_dns_record }}
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ route53_dns_record }}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
    wait: true
  delegate_to: localhost
