---

- name: Create secret
  redhat.openshift.k8s:
    template: templates/secrets.yaml.j2
  register: _create_secret
  retries: 30
  delay: 10
  
- name: Create CertManager
  redhat.openshift.k8s:
    definition: "{{ _certmanager }}"

- name: Create ClusterIssuer
  redhat.openshift.k8s:
    template: templates/clusterissuer.yaml.j2
  register: _create_clusterissuer
  retries: 30
  delay: 10

- name: Request certificates
  redhat.openshift.k8s:
    template: templates/certificates.yaml.j2

- name: Update ingress
  redhat.openshift.k8s:
    definition: "{{ _ingresscontroller }}"
