---

    - name: Download ISO
      become: false
      run_once: true
      block:
        - name: Generating an access token
          uri:
            url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
            method: POST
            body_format: form-urlencoded
            return_content: true
            body:
              grant_type: "refresh_token"
              client_id: "rhsm-api"
              refresh_token: "{{ offline_token }}"
          register: temp_token
          until: temp_token is not failed
          retries: 15
          delay: 20

        - name: Download RHEL ISO
          delegate_to: localhost
          get_url:
            url: "https://api.access.redhat.com/management/v1/images/{{ provided_sha_value_rhel_iso }}/download"
            headers:
              accept: "application/json"
              Authorization: "Bearer {{ temp_token.json.access_token }}"
            dest: "rhel.iso"
            checksum: "sha256: {{ provided_sha_value_rhel_iso }}"
          register: download_rhel_iso
          async: 600  
          poll: 0  

        - name: Check for download completion
          delegate_to: localhost
          async_status:
            jid: "{{ download_rhel_iso.ansible_job_id }}"
          register: job_result
          until: job_result.finished
          retries: 60  
          delay: 10  

        - name: Handle download status
          debug:
            var: download_rhel_iso
          when: download_rhel_iso.failed
