---

- name: setup image builder, compose images
  hosts:
    - edge_management
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
  vars:
    image_builder_http_port: 18080
  become: true
  pre_tasks:
    - name: rhel8 tasks
      when:
        - ansible_distribution_major_version|int == 8
      block:
        - name: workaround for https://access.redhat.com/solutions/6973651
          ansible.builtin.dnf:
            name: python36
        - name: workaround for not actually supporting dnf modules
          ansible.builtin.shell:
            cmd: dnf module enable nodejs:16 -y
          changed_when: false

    - name: use role to setup Image Builder
      ansible.builtin.include_role:
        name: infra.osbuild.setup_server

  tasks:
    - name: handle image builder being image builder
      block:
        - name: build images via builder role
          ansible.builtin.include_role:
            name: ../roles/infra_osbuild_builder_wrapper
          vars:
            builder_compose_type: "{{ image.type }}"
            builder_compose_pkgs: "{{ image.packages }}"
            builder_custom_repos: "{{ image.repos | default('[]') }}"
            builder_blueprint_distro: "{{ image.distro | default(omit) }}"
            builder_request_timeout: 300
          loop: "{{ images_to_compose }}"
          loop_control:
            loop_var: image
          when:
            - ansible_distribution_major_version|int == 8 or
              ansible_distribution_major_version|int == 9
      rescue:
        - name: try again
          ansible.builtin.include_role:
            name: ../roles/infra_osbuild_builder_wrapper
          vars:
            builder_compose_type: "{{ image.type }}"
            builder_compose_pkgs: "{{ image.packages }}"
            builder_custom_repos: "{{ image.repos | default('[]') }}"
            builder_blueprint_distro: "{{ image.distro | default(omit) }}"
            builder_request_timeout: 600
          loop: "{{ images_to_compose }}"
          loop_control:
            loop_var: image
          when:
            - ansible_distribution_major_version|int == 8 or
              ansible_distribution_major_version|int == 9
        - name: print warning
          ansible.builtin.debug:
            msg: "Ansible block saved Image Buider, confirm images composed correctly"

  post_tasks:
    - name: adjust for non-standard port
      when:
        - image_builder_http_port is defined
      block:
        - name: adjust the standard listening port
          ansible.builtin.lineinfile:
            path: /etc/httpd/conf/httpd.conf
            regexp: '^Listen'
            line: 'Listen {{ image_builder_http_port }}'
          register: _httpd_config
        - name: allow bind to new port
          community.general.seport:
            ports: "{{ image_builder_http_port }}"
            proto: tcp
            setype: http_port_t
            state: present
        - name: allow port through firewalld
          ansible.posix.firewalld:
            permanent: true
            immediate: true
            port: "{{ image_builder_http_port }}/tcp"
            state: enabled
        - name: restart httpd
          ansible.builtin.systemd:
            name: httpd
            state: restarted
          when:
            - _httpd_config.changed is defined
            - _httpd_config.changed
