---

- name: allow remote external access to workshop services
  hosts:
    - edge_remote_management
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
  become: true
  tasks:
    - name: allow ports through firewall
      ansible.posix.firewalld:
        port: "{{ external_service.port }}/{{ external_service.protocol | default('tcp') }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ allowed_external_remote_services }}"
      loop_control:
        loop_var: external_service
      when: allowed_external_remote_services is defined
    - block:
      - name: create password in ec2-user if we created an AWS server
        shell: |
          echo {{ admin_password }} | /usr/bin/passwd ec2-user --stdin

      - name: Allow Password Authentication
        ansible.builtin.lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^#?PasswordAuthentication'
          line: 'PasswordAuthentication yes'
          state: present
      - name: Restart SSH Service
        ansible.builtin.service:
          name: sshd
          state: restarted
      become: true
      when:
        - run_in_aws is defined
        - run_in_aws | bool