---

- name: allow access to workshop services
  hosts:
    - edge_management
    - edge_local_management
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
  become: true
  tasks:
    - name: allow ports through firewall
      ansible.posix.firewalld:
        port: "{{ external_service.port }}/{{ external_service.protocol | default('tcp') }}"
        zone: external
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ allowed_external_services }}"
      loop_control:
        loop_var: external_service
      when: allowed_external_services is defined
    - name: Add entries to /etc/hosts
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_host }} {{ item.value.domain }}"
      loop: "{{ route53_domains | dict2items }}"
    - name: set local /etc/host for external services
      become: true
      lineinfile:
        dest: /etc/hosts
        line: "{{ edge_remote_management_ext_ip }} {{ item.value.domain }}"
      loop: "{{ route53_domains | dict2items }}"
      when:
        - run_in_aws is defined
        - run_in_aws | bool