---

- name: allow remote external access to workshop services
  hosts:
    - edge_remote_management
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
  become: true
  tasks:
    - name: allow ports through firewall
      ansible.posix.firewalld:
        port: "{{ external_service.port }}/{{ external_service.protocol | default('tcp') }}"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ allowed_external_remote_services }}"
      loop_control:
        loop_var: external_service
      when: allowed_external_remote_services is defined