---

- name: setup gitea
  hosts:
    - edge_management
    - edge_remote_management
  vars_files:
    - "{{ playbook_dir }}/workshop_vars/{{ workshop_type }}.yml"
    - "{{ playbook_dir }}/demo_vars/{{ demo_type }}.yml"
  tasks:
    - name: include gitea setup role
      ansible.builtin.include_role:
        name: ../roles/setup_gitea
