---

- name: Create namespace {{ _namespace.metadata.name }}
  redhat.openshift.k8s:
    definition: "{{ _namespace }}"

- name: Create operator group {{ _operator_group }}
  redhat.openshift.k8s:
    definition: "{{ _operator_group }}"

- name: Install operator
  redhat.openshift.k8s:
    definition: "{{ _subscription }}"

- name: Create instance of controller
  redhat.openshift.k8s:
    definition: "{{ _controller }}"
  register: _instance_deploy
  until:
    - not _instance_deploy.failed
  retries: 30
  delay: 30
